package com.erp.system.production.repository.production_standard_information.standard_information_management.impl;

import com.erp.system.common.annotation.Component;
import com.erp.system.common.generic_repository.impl.GenericRepositoryImpl;
import com.erp.system.production.model.production_standard_information.standard_information_management.ProductionEquipmentStandard;
import com.erp.system.production.repository.production_standard_information.standard_information_management.ProductionEquipmentStandardRepository;

@Component
public class ProductionEquipmentStandardRepositoryImpl extends GenericRepositoryImpl<ProductionEquipmentStandard> implements ProductionEquipmentStandardRepository {
    private ProductionEquipmentStandardRepositoryImpl() { super(ProductionEquipmentStandard.class);}
}
